### ISSUE TITLE
Milestone 2 feedbacks

### ISSUE THREAD

**Issue by sirine-chahma** [STAT547-UBC-2019-20/team11_akhan#17]
First of all, great work! Here are some feedbacks for your milestone 2 : 

- Even if you are the only person in your group, try to use issues to remind yourself what you still have to do (this can be useful for you in the future).
- your HTML and a PDF reports should be exported to the root of the repository (not in a folder).
- In the introduction of your report, try to link your dataset to a more meaningful word (dataset for instance)
- Your second and your fourth plots didn't render in the `.md` file.
- Try to be more precise in your EDA (use some figures in your analysis. But be careful, those figures shouldn't be “hard-coded”)
- Overall, very nice plots! 
- There should be a script to knit your DRAFT of your final report (an Rmarkdown file) to an HTML and PDF file. There should be some instruction of how to run this file in the README file. 

Overall, well done!

**Comment by almas2019** [comment]
Hi Sirine, 
Thank you for your feedback, but I was wondering if you could provide some clarification on some points:

> Try to be more precise in your EDA (use some figures in your analysis. But be careful, those figures shouldn't be “hard-coded”)" , 

What do you mean by more precise, and in regards to figures, I was trying to follow the directions in the example, but I'm not sure what you mean here with hard coded? Also, I thought I used figures, is there additional figures I should include?

 >In the introduction of your report, try to link your dataset to a more meaningful word (dataset for instance)
 Is this related to the variable name in the code?

Thank you.

**Comment by sirine-chahma** [comment]
Sorry, I just saw your questions...
For the first point, I just meant give a conclusion of your EDA with some numbers to emphasize your findings. For example, when you study the spread of the final grades, you can say "The maximum of the density corresponds to a final grade of 10.5)". But you should write this value yourself, you should import it. Is it clearer? :)
And for the second point, yes, I was just refering to the name of the variable, but I can see you fixed it!
