### ISSUE TITLE
Linear Regression?

### ISSUE THREAD

**Issue by almas2019** [STAT547-UBC-2019-20/team11_akhan#19]
Hi @firasm  and @sirine-chahma,

I've discussed this Firas a bit, but I was wondering if linear regression is the best way to look at a numeric response (grades from 1-20), aka the _y_,  and a likert scale predictor (1 to 5, from little to a lot of alcohol use), aka the _x_ variable. I don't think logisitic regression is the right case here either as the response is not a binomial yes/no outcome. Would this be a non-parametric test, or is linear regression still okay in this case?

![image](https://user-images.githubusercontent.com/47234185/76815723-a1d72c00-67bb-11ea-8f10-4200fc6d1aca.png)

When I run linear regression this is the line I get: 

![image](https://user-images.githubusercontent.com/47234185/76816756-51ad9900-67be-11ea-85f7-cf514903086e.png)

**Comment by firasm** [comment]
Hi @almas2019,

Thanks for moving the discussion to the GitHub repo! You're right that by default a logistic regression is for binary data, but there are several different flavours of logistic regression.

I think (@sirine-chahma can correct me if she has a better suggestion) an ordinal logistic regression is most appropriate here. 

[Here's a tutorial](https://stats.idre.ucla.edu/r/dae/ordinal-logistic-regression/) with a walkthrough and detailed explanation of how to run the analysis, as well as how to interpret it.

Also, just as a note there is over plotting on your plots, I'd suggest jittering on the x-axis.

**Comment by almas2019** [comment]
Hi @firasm , 

Thank you for your suggestion. I'm still confused regarding the tutorial, as again in the examples the tutorial gives, it seems like their response variable is a likert scale, while its the opposite for me. Like for ex.  they look at how likely is someone to apply (likert scale from 1 to 3) as their response/outcome variable but GPA and other factors as their predictor. In my case it would be the opposite, the GPA is the response/outcome, and the likert scale(how likely to apply or how much alcohol use) would be the predictor variable. I'm not sure if ordinal logistic works in this case as the outcome is a numeric. 
Apologies for the confusion, but I'm not sure if I should convert the likert scale items to 4 contrasting dummy variables(similar to categories [here](https://psychstat3.missouristate.edu/Documents/MultiBook3/Mlt07.htm) , use them as is, or do something else. I may also be overthinking this. 
 Also my jittered plot, for better explanation.
![image](https://user-images.githubusercontent.com/47234185/76820520-aa822f00-67c8-11ea-8ab6-e59cf53d861f.png)

Thank you for your help,
-Almas

**Comment by sirine-chahma** [comment]
Hi @almas2019 ! Sorry for the late reply. 

If you just want to observe the general influence of drinking over the final grade, you can just do a linear regression as you did. In this case, you would assume a linear relation between your covariate (the number of times a student drinks), and the response (the final grade). If you assume a linear relation, the interpretation of the coefficients you'll have from your linear regression is going to be very simple. 

If you want a more accurate but more complex model, you can "consider your feature as categorical", and use dummy variables. In this case, you wouldn't use the order that exists in your covariate, and you would have two coefficients (slope and intercept), for each one of your categories (so you would have 10 coefficients in total here). But this would allow you to have changes in your trend (for example you could have a high grade for X=1, a low one for X=2, and a high one for X=3). Those changes wouldn't be captured with a simple linear model.
