### ISSUE TITLE
Peer Review of Milestone 2

### ISSUE THREAD

**Issue by lucymosquera** [STAT547-UBC-2019-20/team11_akhan#20]
Hello! 

Great job on your milestone 2 submission, the work seems to be reproducible and well documented.

* Is the repository organized in a useful and sensible way? _Yes, good organization of repo with reasonably number of subfolder. Could be helpful to add brief READMEs to subfolders, but not a necessity_
* Is there a Usage section in the README? _Yes, it worked for me on the first try, producing the various 'success' messages_
* Do the scripts run to completion as described in the README? _Mostly. For me the EDA script did not produce any new plots. Additionally, it seemed like there were more plots in the 'images' folder than would be produced by the EDA script._
* Do the scripts produce the expected output? _Mostly!_
* Are the scripts and functions appropriately documented? _Yes the scripts and functions look well documented, it is fairly easy to follow along with what each script does_
* Does it take a long time for the analysis to run? Are there tasks that could be vectorized to make things faster? _Not very long whatsoever!_

Great job, and good luck with the rest of the semester!

**Comment by almas2019** [comment]
Hi @lucymosquera  thank you for your feedback.

I will try to add readmes to subfolders as future work.
