### ISSUE TITLE
Feedbacks milestone 4

### ISSUE THREAD

**Issue by sirine-chahma** [STAT547-UBC-2019-20/team11_akhan#33]
Great implementation of the feedbacks! 

- don't forget to close your issues once they are no longer relevant 
- great description of your app! And I really like the usage scenario, it is very relevant! 
- The sketch of your dashboard is great! However, it seems like a lot of work (but it's totally doable I think), good luck with making it! I'm sure your dashboard is going to be very efficient! 
- The `app.R` file should be in the root of your repo.

**Comment by almas2019** [comment]
@sirine-chahma and @firasm  I was wondering if it is possible to change some features of the dashboard from the initial sketch. Initially I wanted to include checkboxes to show/hide graphs, but I have tried everything to get this feature to work and it doesn't seem to be working. I have tabs and plots, but I'm not sure how faithful I have to be to the original sketch.

**Comment by firasm** [comment]
Sure - you're more than welcome to update your plans based on feedback and feasibility.

**Comment by firasm** [comment]
btw, interesting idea to show/hide graphs! I'm not sure if I've ever encountered that before, not even sure it's possible without hacking it a bit.

**Comment by almas2019** [comment]
I've been trying to do this : https://stackoverflow.com/questions/50852743/plotly-figure-hide-and-display
Which is for the python version of dash but I'm not succeeding, so I think I will remove the checkboxes because of limited feasibility

**Comment by firasm** [comment]
Oh that's right - you can just hide the whole div! I remember doing this a few weeks ago with a group of students last term. 

Perhaps I can give you hand in office hours if you're keen on implementing it.

**Comment by almas2019** [comment]
Thank you for your feedback today. I implemented the side by side plots on my first tab!
