### ISSUE TITLE
Feedback from Dash from Eve W.

### ISSUE THREAD

**Issue by almas2019** [STAT547-UBC-2019-20/team11_akhan#35]
She noted that I had a double header and should include a description at the top.

**Comment by evelynjulia** [comment]
If you move the description to above the tabs it bring it above and on both pages!
In this section of your code:
https://github.com/STAT547-UBC-2019-20/team11_akhan/blob/master/app.R#L174-L190

**Comment by almas2019** [comment]
@evelynjulia  Thank you for your feedback, I opted to keep the description tab at the bottom, but I included a couple of sentences at the top of each tab to describe what information each tab shows.
